CREATE TABLE IF NOT EXISTS COINS (
                                     COIN_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                     COIN_NAME VARCHAR(255) NOT NULL,
                                     MIN_TRADING_QTY DOUBLE,
                                     MAX_TRADING_QTY DOUBLE,
                                     MIN_LEVERAGE INT,
                                     MAX_LEVERAGE INT,
                                     IS_WORK BOOLEAN DEFAULT FALSE,
                                     TIMEFRAME VARCHAR(50)
);


CREATE TABLE IF NOT EXISTS STRATEGY_IN_WORK
(
    STRATEGY_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    COIN_ID BIGINT NOT NULL,
    TIMEFRAME VARCHAR(255),
    EMA INT,
    CCI INT,
    RATIO DOUBLE,
    LEVERAGE INT,
    MAX_ORDERS INT,
    IS_ACTIVE BOOLEAN,
    FOREIGN KEY (COIN_ID) REFERENCES COINS(COIN_ID)
);